# Type stub for drdo_map C++ pybind11 module
from typing import Optional, Dict, Any

def reset_map() -> None: ...
def insert_point(x: float, y: float, z: float, label: int, robot_x: float, robot_y: float, frame_ts: int) -> bool: ...
def query_world(wx: float, wy: float) -> Optional[Dict[str, Any]]: ...
def decay_kernel(current_frame: int) -> int: ...
def classify_and_score_all(ground_z: float = 0.0) -> int: ...
def valid_cell_count() -> int: ...
