# Type stub for drdo_map C++ pybind11 module
from typing import Optional, Dict, Any
import numpy

def reset_map() -> None: ...
def insert_point(x: float, y: float, z: float, label: int, robot_x: float, robot_y: float, frame_ts: int, ground_z: float = 0.0) -> bool: ...
def query_world(wx: float, wy: float) -> Optional[Dict[str, Any]]: ...
def decay_kernel(current_frame: int) -> int: ...
def classify_and_score_all(ground_z: float = 0.0) -> int: ...
def classify_dirty(ground_z: float = 0.0) -> int: ...
def purge_distant(robot_x: float, robot_y: float, margin_m: float = 20.0) -> int: ...
def valid_cell_count() -> int: ...
def load_factor() -> float: ...
def insert_fail_count() -> int: ...
def insert_points(points: "numpy.ndarray", robot_x: float, robot_y: float, frame_ts: int, ground_z: float = 0.0) -> int: ...
def export_cells() -> Dict[str, "numpy.ndarray"]: ...
CELL_RESOLUTIONS: tuple
LEVEL_OUTER_R: tuple
CELL_BYTES: int
POOL_CELLS: int
